name: "MobiledgeX Deploy"
description: "Deploy app to the MobiledgeX platform"

inputs:
  setup:
    description: The setup to deploy the app to
    required: true
    default: main
  username:
    description: Console username
    required: true
  password:
    description: Console password
    required: true
  appconfig:
    description: Path to app config
    required: true
    default: .mobiledgex/app.yml
  appinstsconfig:
    description: Path to app instances config
    required: true
    default: .mobiledgex/appinsts.yml

outputs:
  setup:
    description: Setup app is deployed in
  image:
    description: Image path for the app
  deployments:
    description: App instance deployments

runs:
  using: docker
  image: Dockerfile
  args:
    - "--setup"
    - ${{ inputs.setup }}
    - "--appconfig"
    - ${{ inputs.appconfig }}
    - "--appinstsconfig"
    - ${{ inputs.appinstsconfig }}
