name: "MobiledgeX Deploy"
description: "Deploy app to the MobiledgeX platform"

inputs:
  setup:
    description: The setup to deploy the app to
    required: true
    default: stage
  username:
    description: Console username
    required: true
  password:
    description: Console password
    required: true
  appname:
    description: Name of the app
    required: true
  appvers:
    description: Version of the app
    required: true
  app-org:
    description: App organization
    required: true
  region:
    description: App region
    required: true
  imagepath:
    description: Path to the docker image
    required: true
  accessports:
    description: List of access ports
    required: true
  defaultflavor:
    description: Default flavor
    required: true

outputs:
  setup:
    description: Setup the app is deployed in
  image:
    description: Image path for the app

runs:
  using: docker
  image: Dockerfile
  args:
    - "--setup"
    - ${{ inputs.setup }}
    - ${{ inputs.appname }}
    - ${{ inputs.appvers }}
    - ${{ inputs.app-org }}
    - ${{ inputs.region }}
    - ${{ inputs.imagepath }}
    - ${{ inputs.accessports }}
    - ${{ inputs.defaultflavor }}
